<style>
    div#page-content{background:#e2e2e2 !important;}
</style>
<div id="page-heading">    

    
</div>
<div class="container">

    <div class="row">
        <div class="col-md-12">
            <p class="text-center">
                <br/>
                <br/>
                <br/>
                <img src="/images/404.png" />
                <br/>
                <span class="text-info" style="font-size:4em;">Error</span>
            </p>
            <p class="text-center">El recurso que usted busca no existe.</p>
            <p class="text-center">comuniquese con el area de desarrollo, gracias.</p>
        </div>
        <div class="col-md-4 col-md-offset-4">
            
            <p class="text-center"><small><a href="/">[ Ir a la pagina de inicio ]</a></small></p>
        </div>
    </div>

</div> <!-- container -->