<script type="text/javascript">
    $(document).ready(function () {
        var source =
        {
            datatype: "json",
            datafields: [
            { name: 'nro',type: 'number'},
            { name: 'id',type: 'number'},
            { name: 'detalle',type: 'string'},
            { name: 'institucion',type: 'string'},
            { name: 'grado',type: 'string'},
            { name: 'numero_titulo',type: 'string'},
            { name: 'nombre_rector',type: 'string'},
            { name: 'fecha_emision',type: 'date'}
            ],
            url: '/index/listPformaciones/',
            cache: false
        };
        var dataAdapter = new $.jqx.dataAdapter(source);
        cargar();   
        function cargar(){
            $("#jqxgrid").jqxGrid(
            {
                width: '100%',
                source: dataAdapter,
                sortable: true,
                altRows: true,
                pageable: true,
                pagerMode: 'advanced',
                showfilterrow: true,
                filterable: true,
                columns: [
                { text: 'Nro', datafield: 'id',filtertype: 'number', width: '5%'},
                { text: 'Detalle', datafield: 'detalle', filtertype: 'input',width: '15%' },
                { text: 'Institución', datafield: 'institucion',filtertype: 'input', width: '70%' },
                { text: 'Editar', datafield: 'Editar', width: '5%',sortable:false, columntype: 'button',filterable:false, cellsrenderer: function () {
                    return "Editar";
                }, buttonclick: function (row) {
                editrow = row;
                var dataRecord = $("#jqxgrid").jqxGrid('getrowdata', editrow);
                $("#titulo").text("Editar");
                $("#id").val(dataRecord.id);
                $("#detalle").val(dataRecord.detalle);
                $("#institucion").val(dataRecord.institucion);
                $('#myModal').modal('show');

            }
        },
        { text: 'Eliminar', datafield: 'Eliminar',width:'5%', sortable:false, columntype: 'button', filterable:false,cellsrenderer: function () {
            return "Eliminar";
        }, buttonclick: function (row) {
            editrow = row;
                var dataRecord = $("#jqxgrid").jqxGrid('getrowdata', editrow);
                $("#id").val(dataRecord.id);
                bootbox.confirm("<strong>¡Mensaje!</strong> Esta seguro de eliminar el registro.", function(result) {
                    if (result==true) {
                        var v=$.ajax({
                            url:'/index/delete/',
                            type:'POST',
                            datatype: 'json',
                            data:{id:$("#id").val()},
                success: function(data) { cargar(); //alert('Guardado Correctamente'); 
                }, //mostramos el error
                error: function() { alert('Se ha producido un error Inesperado'); }
            });
                    }
                });
            }
        }
        ]
    });

}

// update the edited row when the user clicks the 'Save' button.
$("#add").click(function(){
    $("#titulo").text("Adicionar");
    $("#id").val("");
    $("#detalle").val("");
    $("#institucion").val("");
    $('#myModal').modal('show');
});

$('#testForm').validate({
    rules: {
        detalle: {
            required: true
        },
        institucion: {
            required: true
        }
    },
    highlight: function (element) {
        $(element).closest('.control-group').removeClass('success').addClass('error');
    },
    success: function (element) {
        //element.text('OK!').addClass('valid').closest('.control-group').removeClass('error').addClass('success');
        element.addClass('valid').closest('.control-group').removeClass('error').addClass('success');
    },
    submitHandler: function (form) {
            
            // var v=$.ajax({
            //     url:'/nivelestructurales/save/',
            //     type:'POST',
            //     datatype: 'json',
            //     data:{id:$("#id").val(),orden:$("#orden").val(),nivel_estructural:$("#nivel_estructural").val()},
            //     success: function(data) { cargar(); //alert(data); 
            //     }, //mostramos el error
            // error: function() { alert('Se ha producido un error Inesperado'); }
            // });
            $('#myModal').modal('hide');
            return false; // ajax used, block the normal submit
        }
});


});
</script>

<div class="row">
    <div class="col-sm-12 animation-stretchRight">
        <div class="widget">
         <div id="chartdiv" style="width: 100%; height: 400px;">

            <div class="row">
                <div class="col-md-12">
                    <div class="block">
                        <div class="block-title">
                            <!-- <h2><strong>Validation</strong> Wizard</h2> -->
                            <h1>
                                <i class="gi gi-dashboard"></i>Pagina de Inicio<br><small>Bienvenido: <?php echo $usuario->nombre.' '.$usuario->app.' '.$usuario->apm; ?></small>
                            </h1>
                        </div>
                        <form id="advanced-wizard" action="page_forms_wizard.php" method="post" class="form-horizontal form-bordered" />
                        <div id="advanced-uno" class="step">
                            <div class="wizard-steps">
                                <div class="row">
                                    <div class="col-xs-1">
                                    </div>
                                    <div class="col-xs-1 active">
                                        <span>Datos Personales</span>
                                    </div>
                                    <div class="col-xs-1">
                                        <span>Formación Academica</span>
                                    </div>
                                    <div class="col-xs-1 ">
                                        <span>Experiencia Laboral General</span>
                                    </div>
                                    <div class="col-xs-1 ">
                                        <span>Experiencia Relacionada al Cargo</span>
                                    </div>
                                    <div class="col-xs-1 ">
                                        <span>Cursos y Seminarios</span>
                                    </div>
                                    <div class="col-xs-1 ">
                                        <span>Manejo de Paquetes de Computación</span>
                                    </div>
                                    <div class="col-xs-1 ">
                                        <span>Idiomas</span>
                                    </div>
                                    <div class="col-xs-1 ">
                                        <span>Docencia</span>
                                    </div>
                                    <div class="col-xs-1 ">
                                        <span>Referencias Personales</span>
                                    </div>
                                    <div class="col-xs-1">
                                    </div>
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-md-6">
                                    <div class="block">
                                        <div class="block-title">
                                            <h2><strong>Datos Personales</strong></h2>
                                        </div>
                                        <dl class="dl-horizontal">
                                            <dt>Puesto al que Postula</dt>
                                            <dd><?php echo $postulante->lugar_postulacion ?></dd>
                                            <dt>Lugar de Postulación</dt>
                                            <dd><?php echo $postulante->lugar_postulacion ?></dd>
                                            <dt>Nombre(s) y Apellidos</dt>
                                            <dd><?php echo $postulante->nombre.' '.$postulante->app. ' '.$postulante->apm ?></dd>
                                            <dt>Sexo</dt>
                                            <dd><?php echo $postulante->sexo ?></dd>
                                            <dt>Cedula de Identidad</dt>
                                            <dd><?php echo $postulante->ci.' '.$postulante->expedido ?></dd>
                                            <dt>Fecha de Nacimiento</dt>
                                            <dd><?php echo $postulante->fecha_nac ?></dd>
                                            <dt>Nacionalidad</dt>
                                            <dd><?php echo $postulante->nacionalidad ?></dd>
                                            <dt>Estado Civil</dt>
                                            <dd><?php echo $postulante->estado_civil ?></dd>
                                            <dt>Libreta Militar</dt>
                                            <dd><?php echo $postulante->libreta_militar ?></dd>
                                            <dt>Empadronamiento</dt>
                                            <dd><?php echo $postulante->empadronamiento ?></dd>
                                            <dt>Parentesco</dt>
                                            <dd><?php echo $postulante->parentesco ?></dd>
                                        </dl>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="block">
                                        <div class="block-title">
                                            <h2><strong>Datos Referenciales</strong></h2>
                                        </div>
                                        <dl class="dl-horizontal">
                                            <dt>Dirección Domicilio</dt>
                                            <dd><?php echo $postulante->direccion ?></dd>
                                            <dt>Teléfono</dt>
                                            <dd><?php echo $postulante->telefono ?></dd>
                                            <dt>Celular</dt>
                                            <dd><?php echo $postulante->celular ?></dd>
                                            <dt>Correo Electronico</dt>
                                            <dd><?php echo $postulante->correo ?></dd>
                                            <dt>Fax</dt>
                                            <dd><?php echo $postulante->fax ?></dd>
                                            <dt>Casilla de Correo</dt>
                                            <dd><?php echo $postulante->casilla ?></dd>
                                        </dl>
                                        <div class="col-md-12 col-md-offset-3">
                                            <!-- <button class="btn btn-sm btn-primary" type="button"></button> -->
                                            <a href="/ppostulantes/" class="btn btn-sm btn-primary">Modificar Datos Personales</a>
                                        </div>
                                    </div>
                                </div>
                            </div>

                        </div>
                        <div id="advanced-dos" class="step">
                            <div class="wizard-steps">
                                <div class="row">
                                    <div class="col-xs-1">
                                    </div>
                                    <div class="col-xs-1 done">
                                        <span>Datos Personales</span>
                                    </div>
                                    <div class="col-xs-1 active">
                                        <span>Formación Academica</span>
                                    </div>
                                    <div class="col-xs-1 ">
                                        <span>Experiencia Laboral General</span>
                                    </div>
                                    <div class="col-xs-1 ">
                                        <span>Experiencia Relacionada al Cargo</span>
                                    </div>
                                    <div class="col-xs-1 ">
                                        <span>Cursos y Seminarios</span>
                                    </div>
                                    <div class="col-xs-1 ">
                                        <span>Manejo de Paquetes de Computación</span>
                                    </div>
                                    <div class="col-xs-1 ">
                                        <span>Idiomas</span>
                                    </div>
                                    <div class="col-xs-1 ">
                                        <span>Docencia</span>
                                    </div>
                                    <div class="col-xs-1 ">
                                        <span>Referencias Personales</span>
                                    </div>
                                    <div class="col-xs-1">
                                    </div>
                                </div>
                            </div>
                            <div style="margin-left: 5px;">
                    <div>
                        <input id="add" type="button" value=" (+) Adicionar" />
                    </div>
                </div>
                <br>
                <div class="table-responsive">
                    <div id="jqxgrid"></div>
                </div>

                <!-- Modal -->
                <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <form class="form-horizontal" id="testForm" data-toggle="validator"/>
                            <div class="modal-header">
                                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                                <h4 class="modal-title" id="titulo">Editar</h4>
                            </div>
                            <div class="modal-body">

                                <input id="id" name="id" type="hidden" />
                                <div class="form-group">
                                    <label class="col-md-3 control-label" for="example-hf-email">Detalle</label>
                                    <div class="col-md-9">
                                        <input id="detalle" name="detalle" type="number" class="form-control"/>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="col-md-3 control-label" for="example-hf-password">Institución</label>
                                    <div class="col-md-9">
                                        <input id="institucion" name="institucion" type="text" class="form-control"/>
                                    </div>
                                </div>

                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
                                <button type="submit" class="btn btn-primary" id="Save">Guardar</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
            <!-- end  modal -->
                        </div>
            <!-- <div id="advanced-tres" class="step">
                <div class="wizard-steps">
                    <div class="row">
                        <div class="col-xs-2 done">
                            <span>Datos Personales</span>
                        </div>
                        <div class="col-xs-2 done">
                            <span>Formación Academica</span>
                        </div>
                        <div class="col-xs-2 active">
                            <span>Experiencia Laboral General</span>
                        </div>
                        <div class="col-xs-2 done">
                            <span>Experiencia Relacionada al Cargo</span>
                        </div>
                        <div class="col-xs-2 done">
                            <span>Cursos y Seminarios</span>
                        </div>
                        <div class="col-xs-2 done">
                            <span>Manejo de Paquetes de Computación</span>
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-md-4 control-label" for="example-advanced-bio">Bio</label>
                    <div class="col-md-8">
                        <textarea id="example-advanced-bio" name="example-advanced-bio" rows="6" class="form-control" placeholder="Tell us your story.."></textarea>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-md-4 control-label" for="example-advanced-newsletter">Newsletter</label>
                    <div class="col-md-6">
                        <div class="checkbox">
                            <label for="example-advanced-newsletter">
                                <input type="checkbox" id="example-advanced-newsletter" name="example-advanced-newsletter" />  Sign up
                            </label>
                        </div>
                    </div>
                </div>
            </div>
            <div id="advanced-cuatro" class="step">
                <div class="wizard-steps">
                    <div class="row">
                        <div class="col-xs-2 done">
                            <span>Datos Personales</span>
                        </div>
                        <div class="col-xs-2 done">
                            <span>Formación Academica</span>
                        </div>
                        <div class="col-xs-2 done">
                            <span>Experiencia Laboral General</span>
                        </div>
                        <div class="col-xs-2 active">
                            <span>Experiencia Relacionada al Cargo</span>
                        </div>
                        <div class="col-xs-2 done">
                            <span>Cursos y Seminarios</span>
                        </div>
                        <div class="col-xs-2 done">
                            <span>Manejo de Paquetes de Computación</span>
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-md-4 control-label" for="example-advanced-bio">Bio</label>
                    <div class="col-md-8">
                        <textarea id="example-advanced-bio" name="example-advanced-bio" rows="6" class="form-control" placeholder="Tell us your story.."></textarea>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-md-4 control-label" for="example-advanced-newsletter">Newsletter</label>
                    <div class="col-md-6">
                        <div class="checkbox">
                            <label for="example-advanced-newsletter">
                                <input type="checkbox" id="example-advanced-newsletter" name="example-advanced-newsletter" />  Sign up
                            </label>
                        </div>
                    </div>
                </div>
            </div>
            <div id="advanced-cinco" class="step">
                <div class="wizard-steps">
                    <div class="row">
                        <div class="col-xs-2 done">
                            <span>Datos Personales</span>
                        </div>
                        <div class="col-xs-2 done">
                            <span>Formación Academica</span>
                        </div>
                        <div class="col-xs-2 done">
                            <span>Experiencia Laboral General</span>
                        </div>
                        <div class="col-xs-2 done">
                            <span>Experiencia Relacionada al Cargo</span>
                        </div>
                        <div class="col-xs-2 active">
                            <span>Cursos y Seminarios</span>
                        </div>
                        <div class="col-xs-2 done">
                            <span>Manejo de Paquetes de Computación</span>
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-md-4 control-label" for="example-advanced-bio">Bio</label>
                    <div class="col-md-8">
                        <textarea id="example-advanced-bio" name="example-advanced-bio" rows="6" class="form-control" placeholder="Tell us your story.."></textarea>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-md-4 control-label" for="example-advanced-newsletter">Newsletter</label>
                    <div class="col-md-6">
                        <div class="checkbox">
                            <label for="example-advanced-newsletter">
                                <input type="checkbox" id="example-advanced-newsletter" name="example-advanced-newsletter" />  Sign up
                            </label>
                        </div>
                    </div>
                </div>
            </div>
            <div id="advanced-seis" class="step">
                <div class="wizard-steps">
                    <div class="row">
                        <div class="col-xs-2 done">
                            <span>Datos Personales</span>
                        </div>
                        <div class="col-xs-2 done">
                            <span>Formación Academica</span>
                        </div>
                        <div class="col-xs-2 done">
                            <span>Experiencia Laboral General</span>
                        </div>
                        <div class="col-xs-2 done">
                            <span>Experiencia Relacionada al Cargo</span>
                        </div>
                        <div class="col-xs-2 done">
                            <span>Cursos y Seminarios</span>
                        </div>
                        <div class="col-xs-2 active">
                            <span>Manejo de Paquetes de Computación</span>
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-md-4 control-label" for="example-advanced-bio">Bio</label>
                    <div class="col-md-8">
                        <textarea id="example-advanced-bio" name="example-advanced-bio" rows="6" class="form-control" placeholder="Tell us your story.."></textarea>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-md-4 control-label" for="example-advanced-newsletter">Newsletter</label>
                    <div class="col-md-6">
                        <div class="checkbox">
                            <label for="example-advanced-newsletter">
                                <input type="checkbox" id="example-advanced-newsletter" name="example-advanced-newsletter" />  Sign up
                            </label>
                        </div>
                    </div>
                </div>
            </div> -->
            <div class="form-group form-actions">
                <div class="col-md-8 col-md-offset-4">
                    <input type="reset" class="btn btn-sm btn-warning" id="back2" value="Back" />
                    <input type="submit" class="btn btn-sm btn-primary" id="next2" value="Next" />
                </div>
            </div>
        </form>
    </div>
</div>
</div>
</div>
</div>
</div>
</div>
<script>!window.jQuery && document.write(unescape('%3Cscript src="/assets/js/vendor/jquery-1.11.0.min.js"%3E%3C/script%3E'));</script>
<script>$(function(){ FormsWizard.init(); });</script>
