<?php echo $variable; ?>
<div class="row">
    <div class="col-sm-12">
        <div class="widget">
         <div id="chartdiv" style="width: 100%; height: 500px;">
            <div class="row">
                <div class="col-md-12">

                    <div class="block-title">
                        <h3 style="color:#2D78D5">
                            <i class="gi gi-dashboard"></i>Bienvenido: <?php echo $usuario->nombre.' '.$usuario->app.' '.$usuario->apm; ?>
                        </h3>
                    </div>
                    <form action="" method="post" id="wizard" class="form-horizontal">
                        <fieldset title="Paso 1">
                            <legend>Datos Personales</legend>
                            <div class="row">
                                <div class="col-md-12"><?php  echo $this->flashSession->output(); ?> </div>
                            </div>
                            <div class="row">
                              <div class="col-md-6">
                                <div class="block">
                                    <div class="block-title">
                                        <h2><strong>Datos Personales</strong></h2>
                                    </div>
                                   <!--  <div class="row">
                                        <div class="col-md-5">
                                            <dt class="pull-right">Puesto al que Postula</dt>
                                        </div>
                                        <div class="col-md-7">
                                            <?php // foreach ($puestopostula as $v) { ?>
                                            <dd><?php // echo $v->cargo ?></dd>    
                                            <?php // } ?>
                                        </div>
                                    </div> -->

                                    <div class="row">
                                        <div class="col-md-5">
                                            <dt class="pull-right">Lugar de Postulaci&oacute;n</dt>
                                        </div>
                                        <div class="col-md-7">
                                            <?php echo $postulante->lugar_postulacion ?>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-md-5">
                                            <dt class="pull-right">Nombre(s) y Apellido(s)</dt>
                                        </div>
                                        <div class="col-md-7">
                                            <?php echo $postulante->nombre.' '.$postulante->app. ' '.$postulante->apm ?>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-md-5">
                                            <dt class="pull-right">Cedula de Identidad</dt>
                                        </div>
                                        <div class="col-md-7">
                                            <?php echo $postulante->ci.' '.$postulante->expedido ?>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-md-5">
                                            <dt class="pull-right">Fecha de Nacimiento</dt>
                                        </div>
                                        <div class="col-md-7">
                                            <?php echo date("d-m-Y",strtotime($postulante->fecha_nac)) ?>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-md-5">
                                            <dt class="pull-right">Nacionalidad</dt>
                                        </div>
                                        <div class="col-md-7">
                                            <?php echo $postulante->nacionalidad ?>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-md-5">
                                            <dt class="pull-right">Estado Civil</dt>
                                        </div>
                                        <div class="col-md-7">
                                            <?php echo $postulante->estado_civil ?>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-md-5">
                                            <dt class="pull-right">Libreta Militar</dt>
                                        </div>
                                        <div class="col-md-7">
                                            <?php echo $postulante->libreta_militar ?>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-md-5">
                                            <dt class="pull-right">Empadronamiento</dt>
                                        </div>
                                        <div class="col-md-7">
                                            <?php echo $postulante->empadronamiento ?>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-md-5">
                                            <dt class="pull-right">Parentesco</dt>
                                        </div>
                                        <div class="col-md-7">
                                            <?php echo $postulante->parentesco ?>
                                        </div>
                                    </div>
                                </div>
                            </div>  
                            <div class="col-md-6">
                                <div class="block">
                                    <div class="block-title">
                                        <h2><strong>Datos Referenciales</strong></h2>
                                    </div>
                                    <div class="row">
                                        <div class="col-md-5">
                                            <dt class="pull-right">Direcci&oacute;n Domicilio</dt>
                                        </div>
                                        <div class="col-md-7">
                                            <?php echo $postulante->direccion ?>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-md-5">
                                            <dt class="pull-right">Tel&eacute;fono o Número de Referencia</dt>
                                        </div>
                                        <div class="col-md-7">
                                            <?php echo $postulante->telefono ?>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-md-5">
                                            <dt class="pull-right">Celular</dt>
                                        </div>
                                        <div class="col-md-7">
                                            <?php echo $postulante->celular ?>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-md-5">
                                            <dt class="pull-right">Correo Electronico</dt>
                                        </div>
                                        <div class="col-md-7">
                                            <?php echo $postulante->correo ?>
                                        </div>
                                    </div>
                                    <!-- <div class="row">
                                        <div class="col-md-5">
                                            <dt class="pull-right">Fax</dt>
                                        </div>
                                        <div class="col-md-7">
                                            <?php // echo $postulante->fax ?>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-md-5">
                                            <dt class="pull-right">Casilla de Correo</dt>
                                        </div>
                                        <div class="col-md-7">
                                            <?php // echo $postulante->casilla ?>
                                        </div>
                                    </div>
                                -->

                                <br>
                                <div class="col-md-12 col-md-offset-3">
                                    <!-- <button class="btn btn-sm btn-primary" type="button"></button> -->
                                    <a href="/ppostulantes/edit/" class="btn btn-sm btn-primary">Modificar Datos Personales</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </fieldset>
                <fieldset title="Paso 2">
                    <legend>Formaci&oacute;n Academica</legend>
                    <div class="row">
                        <div class="form-group form-actions">
                            <div class="col-xs-12">
                                <button class="btn btn-sm btn-primary" type="button" id="add_formacion"><i class="fa fa-plus fa-fw"></i>Adicionar</button>
                                <button class="btn btn-sm btn-warning" type="button" id="edit_formacion"><i class="fa fa-pencil fa-fw"></i> Editar</button>
                                <button class="btn btn-sm btn-danger" type="button" id="delete_formacion"><i class="fa fa-trash-o fa-fw"></i> Eliminar</button>
                            </div>
                        </div>

                        <div class="table-responsive">
                            <div id="jqxgridPformaciones"></div>
                        </div>
                    </div>
                </fieldset>
                <fieldset title="Paso 3">
                    <legend>Experiencia Laboral General</legend>
                    <div class="row">
                     <div class="form-group form-actions">
                        <div class="col-xs-12">
                            <button class="btn btn-sm btn-primary" type="button" id="add_explabgeneral"><i class="fa fa-plus fa-fw"></i>Adicionar</button>
                            <button class="btn btn-sm btn-warning" type="button" id="edit_explabgeneral"><i class="fa fa-pencil fa-fw"></i> Editar</button>
                            <button class="btn btn-sm btn-danger" type="button" id="delete_explabgeneral"><i class="fa fa-trash-o fa-fw"></i> Eliminar</button>
                        </div>
                    </div>

                    <div class="table-responsive">
                        <div id="jqxgridPexplabgeneral"></div>
                    </div>
                </div> 
            </fieldset>
            <?php 
            $desabilitar = '';
            if (count($puestopostula)<=0) { 
                $desabilitar = 'disabled';
            }
            ?>          
            <fieldset title="Paso 4" <?php echo $desabilitar ?>>
                <legend>Experiencia Relacionada al Cargo</legend>
                <div class="row">
                    <div class="form-group form-actions">
                        <div class="col-xs-12">
                            <button class="btn btn-sm btn-primary" type="button" id="add_explabespecifica"><i class="fa fa-plus fa-fw"></i>Adicionar</button>
                            <button class="btn btn-sm btn-warning" type="button" id="edit_explabespecifica"><i class="fa fa-pencil fa-fw"></i> Editar</button>
                            <button class="btn btn-sm btn-danger" type="button" id="delete_explabespecifica"><i class="fa fa-trash-o fa-fw"></i> Eliminar</button>
                        </div>
                    </div>
                </div>

                <?php if (count($puestopostula)<=0) { ?>
                <div class="row">
                    <div class="col-xs-12">
                        <div class="alert alert-warning alert-dismissable">
                            <button class="close" aria-hidden="true" data-dismiss="alert" type="button">×</button>
                            <h4>
                                <i class="fa fa-info-circle"></i>
                                Información
                            </h4>
                            Estimado Postulante. Actualmente no hay ningun cargo dentro la convocatoria. Pero usted puede realizar el registro y llenado de su postulación para pasas por el proceso de selección, para futuras convocatorias.
                        </div>    
                    </div>
                </div>
                <?php } ?>
                <div class="row">
                    <div class="table-responsive">
                        <input type="hidden" name="nro_puestos" id="nro_puestos" value="<?php echo count($puestopostula) ?>">
                        <input type="hidden" name="listposseguimiento" id="listposseguimiento" value="<?php echo count($listposseguimiento) ?>">
                        <div id="jqxgridPexplabespecifica"></div>
                    </div>
                </div> 
            </fieldset>
          
            <fieldset title="Paso 5">
                <legend>Cursos y Seminarios</legend>
                <div class="row">
                    <div class="form-group form-actions">
                        <div class="col-xs-12">
                            <button class="btn btn-sm btn-primary" type="button" id="add_curso"><i class="fa fa-plus fa-fw"></i>Adicionar</button>
                            <button class="btn btn-sm btn-warning" type="button" id="edit_curso"><i class="fa fa-pencil fa-fw"></i> Editar</button>
                            <button class="btn btn-sm btn-danger" type="button" id="delete_curso"><i class="fa fa-trash-o fa-fw"></i> Eliminar</button>
                        </div>
                    </div>

                    <div class="table-responsive">
                        <div id="jqxgridPcurso"></div>
                    </div>
                </div> 
            </fieldset>
            <fieldset title="Paso 6">
                <legend>Manejo de Paquetes de Computaci&oacute;n</legend>
                <div class="row">
                    <div class="form-group form-actions">
                        <div class="col-xs-12">
                            <button class="btn btn-sm btn-primary" type="button" id="add_paquete"><i class="fa fa-plus fa-fw"></i>Adicionar</button>
                            <button class="btn btn-sm btn-warning" type="button" id="edit_paquete"><i class="fa fa-pencil fa-fw"></i> Editar</button>
                            <button class="btn btn-sm btn-danger" type="button" id="delete_paquete"><i class="fa fa-trash-o fa-fw"></i> Eliminar</button>
                        </div>
                    </div>

                    <div class="table-responsive">
                        <div id="jqxgridPpaquete"></div>
                    </div>
                </div> 
            </fieldset>
            <fieldset title="Paso 7">
                <legend>Idiomas</legend>
                <div class="row">
                    <div class="form-group form-actions">
                        <div class="col-xs-12">
                            <button class="btn btn-sm btn-primary" type="button" id="add_idioma"><i class="fa fa-plus fa-fw"></i>Adicionar</button>
                            <button class="btn btn-sm btn-warning" type="button" id="edit_idioma"><i class="fa fa-pencil fa-fw"></i> Editar</button>
                            <button class="btn btn-sm btn-danger" type="button" id="delete_idioma"><i class="fa fa-trash-o fa-fw"></i> Eliminar</button>
                        </div>
                    </div>

                    <div class="table-responsive">
                        <div id="jqxgridPidioma"></div>
                    </div>
                </div> 
            </fieldset>
            <fieldset title="Paso 8">
                <legend>Docencia</legend>
                <div class="row">
                    <div class="form-group form-actions">
                        <div class="col-xs-12">
                            <button class="btn btn-sm btn-primary" type="button" id="add_docencia"><i class="fa fa-plus fa-fw"></i>Adicionar</button>
                            <button class="btn btn-sm btn-warning" type="button" id="edit_docencia"><i class="fa fa-pencil fa-fw"></i> Editar</button>
                            <button class="btn btn-sm btn-danger" type="button" id="delete_docencia"><i class="fa fa-trash-o fa-fw"></i> Eliminar</button>
                        </div>
                    </div>

                    <div class="table-responsive">
                        <div id="jqxgridPdocencia"></div>
                    </div>
                </div> 
            </fieldset>
            <fieldset title="Paso 9">
                <legend>Referencias Laborales</legend>
                <div class="row">
                    <div class="form-group form-actions">
                        <div class="col-xs-12">
                            <button class="btn btn-sm btn-primary" type="button" id="add_referencia"><i class="fa fa-plus fa-fw"></i>Adicionar</button>
                            <button class="btn btn-sm btn-warning" type="button" id="edit_referencia"><i class="fa fa-pencil fa-fw"></i> Editar</button>
                            <button class="btn btn-sm btn-danger" type="button" id="delete_referencia"><i class="fa fa-trash-o fa-fw"></i> Eliminar</button>
                        </div>
                    </div>

                    <div class="table-responsive">
                        <div id="jqxgridPreferencia"></div>
                    </div>
                </div> 
            </fieldset>
            <fieldset title="Paso 10">
                <legend>Referencias Personales</legend>
                <div class="row">
                    <div class="form-group form-actions">
                        <div class="col-xs-12">
                            <button class="btn btn-sm btn-primary" type="button" id="add_referenciapersonal"><i class="fa fa-plus fa-fw"></i>Adicionar</button>
                            <button class="btn btn-sm btn-warning" type="button" id="edit_referenciapersonal"><i class="fa fa-pencil fa-fw"></i> Editar</button>
                            <button class="btn btn-sm btn-danger" type="button" id="delete_referenciapersonal"><i class="fa fa-trash-o fa-fw"></i> Eliminar</button>
                        </div>
                    </div>

                    <div class="table-responsive">
                        <div id="jqxgridPreferenciapersonal"></div>
                    </div>
                </div> 
            </fieldset>

            <!-- <input type="submit" name="submit" onclick="return confirm('Esta seguro de de finalizar la postulaci&oacute;n?. Una vez finalizada no podra realizar ningun cambio')" class="finish btn-success btn" title="Finalizar para guardar la postulaci&oacute;n a un cargo" value="Finalizar Postulaci&oacute;n" /> -->

            <input type="submit" name="submit" class="finish btn-success btn" title="Finalizar para guardar la postulaci&oacute;n a un cargo" value="Finalizar Postulaci&oacute;n" />
        </form>
    </div>
</div>
</div>
</div>
</div>
</div>
<!-- Modal Formacion  academica-->
<div class="modal fade" id="myModal_Pformaciones" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <form class="form-horizontal" id="testForm_pformacion" data-toggle="validator"/>
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                <h4 class="modal-title" id="titulo">Editar</h4>
            </div>
            <div class="modal-body">

                <input id="pformacion_id" name="pformacion_id" type="hidden" />
                <div class="form-group">
                    <label class="col-md-3 control-label" >Formaci&oacute;n Academica</label>
                    <div class="col-md-9">
                        <?php echo $detalle ?>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-md-3 control-label" >Documento</label>
                    <div class="col-md-9">
                        <?php echo $documento ?>
                    </div>
                </div>
             <!--    <div class="form-group">
                    <label class="col-md-3 control-label" >Gesti&oacute;n</label>
                    <div class="col-md-9">
                        <?php echo $gestion ?>
                    </div>
                </div> -->
                <div class="form-group">
                    <label class="col-md-3 control-label" >Instituci&oacute;n</label>
                    <div class="col-md-9">
                        <input id="institucion" name="institucion" type="text" class="form-control" placeholder="Ej.: Universidad Mayor de San Andres"/>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-md-3 control-label" >Grado o Titulo Obtenido</label>
                    <div class="col-md-9">
                        <input id="grado" name="grado" type="text" class="form-control" placeholder="Ej.: Ingeniero Hidraulico"/>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-md-3 control-label" >Numero Titulo</label>
                    <div class="col-md-9">
                        <input id="numero_titulo" name="numero_titulo" type="text" class="form-control" placeholder=""/>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-md-3 control-label" >Fecha Emisi&oacute;nxx</label>
                    <div class="col-md-9">
                        <input type="text" id="fecha_emision" name="fecha_emision" value="<?php echo date("d-m-Y") ?>" class="form-control input-datepicker-close" data-date-format="dd-mm-yyyy" placeholder="dd-mm-yyyy" />
                    </div>
                </div>

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
                <button type="submit" class="btn btn-primary" id="Save">Guardar</button>
            </div>
        </form>
    </div>
</div>
</div>
<!-- end  modal -->

<!-- Modal Exp lab general-->
<div class="modal fade" id="myModal_Pexplabgeneral" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <form class="form-horizontal" id="testForm_pexplabgeneral" data-toggle="validator"/>
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                <h4 class="modal-title" id="titulo_explabgeneral">Editar</h4>
            </div>
            <div class="modal-body">

                <input id="pexplabgeneral_id" name="pexplabgeneral_id" type="hidden" />
                <div class="form-group">
                    <label class="col-md-3 control-label" >Desde</label>
                    <div class="col-md-5">
                        <?php echo $mes_desde ?>
                    </div>
                    <div class="col-md-4">
                        <?php echo $gestion_desde ?>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-md-3 control-label" >Hasta</label>
                    <div class="col-md-5">
                        <?php echo $mes_hasta ?>
                    </div>
                    <div class="col-md-4">
                        <?php echo $gestion_hasta ?>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-md-3 control-label" >Cargo</label>
                    <div class="col-md-9">
                        <input id="cargo" name="cargo" type="text" class="form-control" placeholder=""/>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-md-3 control-label" >Empresa o Instituci&oacute;n</label>
                    <div class="col-md-9">
                        <input id="empresa" name="empresa" type="text" class="form-control" placeholder=""/>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-md-3 control-label" >Motivo Retiro</label>
                    <div class="col-md-9">
                        <input id="motivo_retiro" name="motivo_retiro" type="text" class="form-control" placeholder=""/>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-md-3 control-label" >Documento Respaldo</label>
                    <div class="col-md-9">
                        <?php echo $doc_respaldo ?>
                    </div>
                </div>

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
                <button type="submit" class="btn btn-primary" id="Save">Guardar</button>
            </div>
        </form>
    </div>
</div>
</div>
<!-- end  modal -->

<!-- Modal Experencia laboral especifica-->
<div class="modal fade" id="myModal_Pexplabespecifica" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <form class="form-horizontal" id="testForm_pexplabespecifica" data-toggle="validator"/>
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                <h4 class="modal-title" id="titulo_explabespecifica">Editar</h4>
            </div>
            <div class="modal-body">

                <input id="pexplabespecifica_id" name="pexplabespecifica_id" type="hidden" />
                <div class="form-group">
                    <label class="col-md-3 control-label" >Para el Puesto</label>
                    <div class="col-md-9">
                        <select name="pospue_explabesp" id="pospue_explabesp" class='form-control'>
                            <?php foreach ($listposseguimiento as $v) { ?>
                            <option value="<?php echo $v->id ?>" proceso_contratacion_id="<?php echo $v->proceso_contratacion_id ?>"><?php echo $v->cargo ?></option>
                            <?php } ?>
                        </select>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-md-3 control-label" >Desde</label>
                    <div class="col-md-5">
                        <?php echo $mes_desde_explabesp ?>
                    </div>
                    <div class="col-md-4">
                        <?php echo $gestion_desde_explabesp ?>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-md-3 control-label" >Hasta</label>
                    <div class="col-md-5">
                        <?php echo $mes_hasta_explabesp ?>
                    </div>
                    <div class="col-md-4">
                        <?php echo $gestion_hasta_explabesp ?>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-md-3 control-label" >Cargo</label>
                    <div class="col-md-9">
                        <input id="cargo_explabesp" name="cargo_explabesp" type="text" class="form-control" placeholder=""/>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-md-3 control-label" >Empresa o Instituci&oacute;n</label>
                    <div class="col-md-9">
                        <input id="institucion_explabesp" name="institucion_explabesp" type="text" class="form-control" placeholder=""/>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-md-3 control-label" >Principales Funciones Desarrolladas</label>
                    <div class="col-md-9">
                        <textarea id="desc_fun_explabesp" name="desc_fun_explabesp" class="form-control" placeholder="">                       
                        </textarea>
                    </div>
                </div>
                
                <div class="form-group">
                    <label class="col-md-3 control-label" >Documento Respaldo</label>
                    <div class="col-md-9">
                        <?php echo $doc_respaldo_explabesp ?>
                    </div>
                </div>

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
                <button type="submit" class="btn btn-primary" id="Save">Guardar</button>
            </div>
        </form>
    </div>
</div>
</div>
<!-- end  modal -->

<!-- Modal Cursos o Seminarios-->
<div class="modal fade" id="myModal_Pcurso" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <form class="form-horizontal" id="testForm_pcurso" data-toggle="validator"/>
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                <h4 class="modal-title" id="titulo_curso">Editar</h4>
            </div>
            <div class="modal-body">

                <input id="pcurso_id" name="pcurso_id" type="hidden" />
                <div class="form-group">
                    <label class="col-md-3 control-label" >Gesti&oacute;n</label>
                    <div class="col-md-9">
                        <?php echo $gestion_curso ?>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-md-3 control-label" >Instituci&oacute;n</label>
                    <div class="col-md-9">
                        <input id="institucion_curso" name="institucion_curso" type="text" class="form-control" placeholder="Ej.: Universidad Mayor de San Andres"/>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-md-3 control-label" >Nombre Curso</label>
                    <div class="col-md-9">
                        <input id="nombre_curso" name="nombre_curso" type="text" class="form-control" placeholder="Ej.: Electromecanica "/>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-md-3 control-label" >Duraci&oacute;n en Horas</label>
                    <div class="col-md-9">
                        <input id="duracion_hrs_curso" name="duracion_hrs_curso" type="number" class="form-control" placeholder=""/>
                    </div>
                </div>

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
                <button type="submit" class="btn btn-primary" id="Save">Guardar</button>
            </div>
        </form>
    </div>
</div>
</div>
<!-- end  modal -->

<!-- Modal Aplicaciones y Paquetes de computacion-->
<div class="modal fade" id="myModal_Ppaquete" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <form class="form-horizontal" id="testForm_ppaquete" data-toggle="validator"/>
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                <h4 class="modal-title" id="titulo_paquete">Editar</h4>
            </div>
            <div class="modal-body">

                <input id="ppaquete_id" name="ppaquete_id" type="hidden" />
                <div class="form-group">
                    <label class="col-md-3 control-label" >Paquete o Aplicaci&oacute;n</label>
                    <div class="col-md-9">
                        <input id="aplicacion_paquete" name="aplicacion_paquete" type="text" class="form-control" placeholder="Ej.: Auto Cad"/>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-md-3 control-label" >Nivel</label>
                    <div class="col-md-9">
                        <?php echo $nivel_paquete ?>
                    </div>
                </div>

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
                <button type="submit" class="btn btn-primary" id="Save">Guardar</button>
            </div>
        </form>
    </div>
</div>
</div>
<!-- end  modal -->

<!-- Modal Idiomas-->
<div class="modal fade" id="myModal_Pidioma" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <form class="form-horizontal" id="testForm_pidioma" data-toggle="validator"/>
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                <h4 class="modal-title" id="titulo_idioma">Editar</h4>
            </div>
            <div class="modal-body">

                <input id="pidioma_id" name="pidioma_id" type="hidden" />
                <div class="form-group">
                    <label class="col-md-3 control-label" >Idioma</label>
                    <div class="col-md-9">
                        <?php echo $idioma ?>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-md-3 control-label" >Lectura</label>
                    <div class="col-md-9">
                        <?php echo $lectura ?>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-md-3 control-label" >Escritura</label>
                    <div class="col-md-9">
                        <?php echo $escritura ?>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-md-3 control-label" >Conversaci&oacute;n</label>
                    <div class="col-md-9">
                        <?php echo $conversacion ?>
                    </div>
                </div>

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
                <button type="submit" class="btn btn-primary" id="Save">Guardar</button>
            </div>
        </form>
    </div>
</div>
</div>
<!-- end  modal -->

<!-- Modal Docencia-->
<div class="modal fade" id="myModal_Pdocencia" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <form class="form-horizontal" id="testForm_pdocencia" data-toggle="validator"/>
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                <h4 class="modal-title" id="titulo_docencia">Editar</h4>
            </div>
            <div class="modal-body">

                <input id="pdocencia_id" name="pdocencia_id" type="hidden" />
                <div class="form-group">
                    <label class="col-md-3 control-label" >Gesti&oacute;n</label>
                    <div class="col-md-9">
                        <?php echo $gestion_docencia ?>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-md-3 control-label" >Instituci&oacute;n</label>
                    <div class="col-md-9">
                       <input id="institucion_docencia" name="institucion_docencia" type="text" class="form-control" placeholder=""/>
                   </div>
               </div>
               <div class="form-group">
                <label class="col-md-3 control-label" >Asignatura</label>
                <div class="col-md-9">
                    <input id="materia_docencia" name="materia_docencia" type="text" class="form-control" placeholder=""/>
                </div>
            </div>
            <div class="form-group">
                <label class="col-md-3 control-label" >Carga Horaria</label>
                <div class="col-md-9">
                    <input id="duracion_docencia" name="duracion_docencia" type="number" class="form-control" placeholder=""/>
                </div>
            </div>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
            <button type="submit" class="btn btn-primary" id="Save">Guardar</button>
        </div>
    </form>
</div>
</div>
</div>
<!-- end  modal -->

<!-- Modal Referencias-->
<div class="modal fade" id="myModal_Preferencia" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <form class="form-horizontal" id="testForm_preferencia" data-toggle="validator"/>
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                <h4 class="modal-title" id="titulo_referencia">Editar</h4>
            </div>
            <div class="modal-body">

                <input id="preferencia_id" name="preferencia_id" type="hidden" />
                <div class="form-group">
                    <label class="col-md-3 control-label" >Nombre(s) y Apellido(s)</label>
                    <div class="col-md-9">
                        <input id="nombres_y_apps_referencia" name="nombres_y_apps_referencia" type="text" class="form-control" placeholder=""/>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-md-3 control-label" >Instituci&oacute;n</label>
                    <div class="col-md-9">
                       <input id="institucion_referencia" name="institucion_referencia" type="text" class="form-control" placeholder=""/>
                   </div>
               </div>
               <div class="form-group">
                <label class="col-md-3 control-label" >Cargo</label>
                <div class="col-md-9">
                    <input id="cargo_referencia" name="cargo_referencia" type="text" class="form-control" placeholder=""/>
                </div>
            </div>
            <div class="form-group">
                <label class="col-md-3 control-label" >Tel&eacute;fono</label>
                <div class="col-md-9">
                    <input id="telefono_referencia" name="telefono_referencia" type="number" class="form-control" placeholder=""/>
                </div>
            </div>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
            <button type="submit" class="btn btn-primary" id="Save">Guardar</button>
        </div>
    </form>
</div>
</div>
</div>
<!-- end  modal -->

<!-- Modal Referencias Personal-->
<div class="modal fade" id="myModal_Preferenciapersonal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <form class="form-horizontal" id="testForm_preferenciapersonal" data-toggle="validator"/>
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                <h4 class="modal-title" id="titulo_referenciapersonal">Editar</h4>
            </div>
            <div class="modal-body">

                <input id="preferenciapersonal_id" name="preferenciapersonal_id" type="hidden" />
                <div class="form-group">
                    <label class="col-md-3 control-label" >Nombre(s) y Apellido(s)</label>
                    <div class="col-md-9">
                        <input id="nombres_y_apps_referenciapersonal" name="nombres_y_apps_referenciapersonal" type="text" class="form-control" placeholder=""/>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-md-3 control-label" >Parentesco</label>
                    <div class="col-md-9">
                       <input id="parentesco_referenciapersonal" name="parentesco_referenciapersonal" type="text" class="form-control" placeholder=""/>
                   </div>
               </div>
               <div class="form-group">
                <label class="col-md-3 control-label" >Tel&eacute;fono</label>
                <div class="col-md-9">
                    <input id="telefono_referenciapersonal" name="telefono_referenciapersonal" type="number" class="form-control" placeholder=""/>
                </div>
            </div>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
            <button type="submit" class="btn btn-primary" id="Save">Guardar</button>
        </div>
    </form>
</div>
</div>
</div>
<!-- end  modal -->


<!-- Modal Referencias Personal-->
<div class="modal fade" id="myModal_seleccionarcargos" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <form class="form-horizontal" id="testForm_seleccionarcargos" data-toggle="validator"/>
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                <h5 class="modal-title" id="titulo_seleccionarcargos">SELECCIONE EL/LOS CARGOS QUE DECEA POSTULARSE</h5>
            </div>
            <div class="modal-body">
                <div class="form-group">
                    <label class="col-md-3 control-label">Seleccione el/los cargos:</label>
                    <div class="col-md-9">
                        <?php foreach ($puestopostula as $v) { ?>
                        <div class="checkbox">
                            <label for="example-checkbox1">
                            <input type="checkbox" class="seguimiento_ids" id="<?php echo $v->id ?>" name="seguimiento_ids[]" value="<?php echo $v->id ?>" /> <?php echo $v->cargo ?>
                            </label>
                        </div>
                        <?php } ?>

                        
                    </div>
                </div>
            </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
            <button type="submit" class="btn btn-primary" id="Save">Guardar</button>
        </div>
    </form>
</div>
</div>
</div>
<!-- end  modal -->



<style type="text/css">
    .datepicker{z-index:1151 !important;}
    
</style>