<div class="row">
	<div class="col-md-12">
		<div class="widget">
			<div class="widget-advanced widget-advanced-alt">
					<!-- <div class="widget-header text-left">
						<img src="/images/0zmr.jpg" alt="background" class="widget-background animation-pulseSlow" />
					</div> -->
					<div class="widget-main">
						<h4>PRINCIPIOS Y VALORES</h4>
						<p>Los principios de “Mi Teleférico” que deben regir el accionar de los trabajadores son:</p>
						<ol>
							<li>Integridad.</li>
							<li>Eficiencia.</li>
							<li>Profesionalidad.</li>
							<li>Transparencia.</li>
							<li>Compromiso.</li>
							<li>Empatia.</li>
						</ol>

						<p>Los valores están sustentados por los principios que guiarán las decisiones y actuaciones de los trabajadores y estos son:</p>
						<ol>
							<li>Responsabilidad.</li>
							<li>Lealtad.</li>
							<li>Eficiencia.</li>
							<li>Compromiso.</li>
							<li>Amistad.</li>
							<li>Tolerancia.</li>
							<li>Proactividad.</li>
						</ol>
					</div>
				</div>
			</div>
		</div>
	</div>