<?php 
$mes_array =array(
                "1" => "ENERO",
                "2"   => "FEBRERO",
                "3" => "MARZO",
                "4" => "ABRIL",
                "5" => "MAYO",
                "6" => "JUNIO",
                "7" => "JULIO",
                "8" => "AGOSTO",
                "9" => "SEPTIEMBRE",
                "10" => "OCTUBRE",
                "11" => "NOVIEMBRE",
                "12" => "DICIEMBRE"
                );

 ?>
<div class="row">
    <div class="col-md-12">

        <div class="block-title">
            <h3 style="color:#2D78D5">
                <i class="gi gi-dashboard"></i>Bienvenido: <?php echo $usuario->nombre.' '.$usuario->app.' '.$usuario->apm; ?>
            </h3>
        </div>
        <div class="row">
            <div class="col-md-12"><?php  echo $this->flashSession->output(); ?> </div>
        </div>
        <div class="row">
          <div class="col-md-6">
            <div class="block">
                <div class="block-title">
                    <h2><strong>Datos Personales</strong></h2>
                </div>
             <!--    <div class="row">
                    <div class="col-md-5">
                        <dt class="pull-right">Puesto al que Postula</dt>
                    </div>
                    <div class="col-md-7">
                        <?php foreach ($puestopostula as $v) { ?>
                        <dd><?php echo $v->cargo ?></dd>    
                        <?php } ?>
                    </div>
                </div> -->

                <div class="row">
                    <div class="col-md-5">
                        <dt class="pull-right">Lugar de Postulación</dt>
                    </div>
                    <div class="col-md-7">
                        <?php echo $postulante->lugar_postulacion ?>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-5">
                        <dt class="pull-right">Nombre(s) y Apellido(s)</dt>
                    </div>
                    <div class="col-md-7">
                        <?php echo $postulante->nombre.' '.$postulante->app. ' '.$postulante->apm ?>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-5">
                        <dt class="pull-right">Cedula de Identidad</dt>
                    </div>
                    <div class="col-md-7">
                        <?php echo $postulante->ci.' '.$postulante->expedido ?>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-5">
                        <dt class="pull-right">Fecha de Nacimiento</dt>
                    </div>
                    <div class="col-md-7">
                        <?php echo date("d-m-Y",strtotime($postulante->fecha_nac)) ?>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-5">
                        <dt class="pull-right">Nacionalidad</dt>
                    </div>
                    <div class="col-md-7">
                        <?php echo $postulante->nacionalidad ?>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-5">
                        <dt class="pull-right">Estado Civil</dt>
                    </div>
                    <div class="col-md-7">
                        <?php echo $postulante->estado_civil ?>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-5">
                        <dt class="pull-right">Libreta Militar</dt>
                    </div>
                    <div class="col-md-7">
                        <?php echo $postulante->libreta_militar ?>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-5">
                        <dt class="pull-right">Empadronamiento</dt>
                    </div>
                    <div class="col-md-7">
                        <?php echo $postulante->empadronamiento ?>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-5">
                        <dt class="pull-right">Parentesco</dt>
                    </div>
                    <div class="col-md-7">
                        <?php echo $postulante->parentesco ?>
                    </div>
                </div>
            </div>
        </div>  
        <div class="col-md-6">
            <div class="block">
                <div class="block-title">
                    <h2><strong>Datos Referenciales</strong></h2>
                </div>
                <div class="row">
                    <div class="col-md-5">
                        <dt class="pull-right">Dirección Domicilio</dt>
                    </div>
                    <div class="col-md-7">
                        <?php echo $postulante->direccion ?>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-5">
                        <dt class="pull-right">Teléfono</dt>
                    </div>
                    <div class="col-md-7">
                        <?php echo $postulante->telefono ?>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-5">
                        <dt class="pull-right">Celular</dt>
                    </div>
                    <div class="col-md-7">
                        <?php echo $postulante->celular ?>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-5">
                        <dt class="pull-right">Correo Electronico</dt>
                    </div>
                    <div class="col-md-7">
                        <?php echo $postulante->correo ?>
                    </div>
                </div>
                <!-- <div class="row">
                    <div class="col-md-5">
                        <dt class="pull-right">Fax</dt>
                    </div>
                    <div class="col-md-7">
                        <?php // echo $postulante->fax ?>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-5">
                        <dt class="pull-right">Casilla de Correo</dt>
                    </div>
                    <div class="col-md-7">
                        <?php // echo $postulante->casilla ?>
                    </div>
                </div> -->
            </div>
        </div>
    </div>
    <div class="row">
        <div class="block">
            <div class="block-title">
                <h2>Formación Academica</h2>
            </div>
            <div class="table-responsive">
                <table id="general-table" class="table table-striped table-vcenter">
                    <thead>
                        <tr>
                            <th class="text-center">#</th>
                            <th>Detalle</th>
                            <!-- <th>Año</th> -->
                            <th>Institución</th>
                            <th>Grado o Titulo Obtenido</th>
                            <th>Número Titulo</th>
                            <th>Fecha Emisión</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php $c=1; ?>
                        <?php foreach ($formacion as $v) { ?>
                        <tr>
                            <td class="text-center"><?php echo $c; $c++; ?></td>
                            <td><?php echo $v->valor_1 ?></td>
                            <!-- <td><?php // echo $v->gestion ?></td> -->
                            <td><?php echo $v->institucion ?></td>
                            <td><?php echo $v->grado ?></td>
                            <td><?php echo $v->numero_titulo ?></td>
                            <td><?php echo date("d-m-Y",strtotime($v->fecha_emision)) ?></td>
                        </tr>
                        <?php } ?>
                    </tbody>

                </table>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="block">
            <div class="block-title">
                <h2>Experiencia Laboral General</h2>
            </div>
            <div class="table-responsive">
                <table id="general-table" class="table table-striped table-vcenter">
                    <thead>
                        <tr>
                            <th class="text-center">#</th>
                            <th>Desde</th>
                            <th>Hasta</th>
                            <th>Cargo</th>
                            <th>Empresa o Institución</th>
                            <th>Motivo de Retiro</th>
                            <th>Documento de Respaldo</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php $c=1; ?>
                        <?php foreach ($explabgeneral as $v) { ?>
                        <tr>
                            <td class="text-center"><?php echo $c; $c++; ?></td>
                            <td><?php echo $mes_array[$v->mes_desde].' - '.$v->gestion_desde ?></td>
                            <td><?php echo $mes_array[$v->mes_hasta].' - '.$v->gestion_hasta ?></td>
                            <td><?php echo $v->cargo ?></td>
                            <td><?php echo $v->empresa ?></td>
                            <td><?php echo $v->motivo_retiro ?></td>
                            <td><?php echo $v->doc_respaldo ?></td>
                        </tr>
                        <?php } ?>
                    </tbody>
                    
                </table>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="block">
            <div class="block-title">
                <h2>Experiencia Relacionada al Cargo</h2>
            </div>
            <div class="table-responsive">
                <table id="general-table" class="table table-striped table-vcenter">
                    <thead>
                        <tr>
                            <th class="text-center">#</th>
                            <th>Puesto</th>
                            <th>Desde</th>
                            <th>Hasta</th>
                            <th>Cargo</th>
                            <th>Empresa o Institución</th>
                            <th>Principales Funciones</th>
                            <th>Documento de Respaldo</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php $c=1; ?>
                        <?php foreach ($explabespecifica as $v) { ?>
                        <tr>
                            <td class="text-center"><?php echo $c; $c++; ?></td>
                            <td><?php echo $v->codigo_proceso ?></td>
                            <td><?php echo $mes_array[$v->mes_desde].' - '.$v->gestion_desde ?></td>
                            <td><?php echo $mes_array[$v->mes_hasta].' - '.$v->gestion_hasta ?></td>
                            <td><?php echo $v->cargo ?></td>
                            <td><?php echo $v->institucion ?></td>
                            <td><?php echo $v->desc_fun ?></td>
                            <td><?php echo $v->doc_respaldo ?></td>
                        </tr>
                        <?php } ?>
                    </tbody>
                    
                </table>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="block">
            <div class="block-title">
                <h2>Cursos y Seminarios</h2>
            </div>
            <div class="table-responsive">
                <table id="general-table" class="table table-striped table-vcenter">
                    <thead>
                        <tr>
                            <th class="text-center">#</th>
                            <th>Gestión</th>
                            <th>Insitución</th>
                            <th>Nombre Curso</th>
                            <th>Duración Horas</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php $c=1; ?>
                        <?php foreach ($curso as $v) { ?>
                        <tr>
                            <td class="text-center"><?php echo $c; $c++; ?></td>
                            <td><?php echo $v->gestion ?></td>
                            <td><?php echo $v->institucion ?></td>
                            <td><?php echo $v->nombre_curso ?></td>
                            <td><?php echo $v->duracion_hrs ?></td>
                        </tr>
                        <?php } ?>
                    </tbody>
                    
                </table>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="block">
            <div class="block-title">
                <h2>Manejo de Paquetes de Computación</h2>
            </div>
            <div class="table-responsive">
                <table id="general-table" class="table table-striped table-vcenter">
                    <thead>
                        <tr>
                            <th class="text-center">#</th>
                            <th>Paquete o Aplicación</th>
                            <th>Nivel</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php $c=1; ?>
                        <?php foreach ($paquete as $v) { ?>
                        <tr>
                            <td class="text-center"><?php echo $c; $c++; ?></td>
                            <td><?php echo $v->aplicacion ?></td>
                            <td><?php echo $v->nivel ?></td>
                        </tr>
                        <?php } ?>
                    </tbody>
                    
                </table>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="block">
            <div class="block-title">
                <h2>Idiomas</h2>
            </div>
            <div class="table-responsive">
                <table id="general-table" class="table table-striped table-vcenter">
                    <thead>
                        <tr>
                            <th class="text-center">#</th>
                            <th>Idioma</th>
                            <th>Lectura</th>
                            <th>Escritura</th>
                            <th>Conversación</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php $c=1; ?>
                        <?php foreach ($idioma as $v) { ?>
                        <tr>
                            <td class="text-center"><?php echo $c; $c++; ?></td>
                            <td><?php echo $v->idioma ?></td>
                            <td><?php echo $v->lectura ?></td>
                            <td><?php echo $v->escritura ?></td>
                            <td><?php echo $v->conversacion?></td>
                        </tr>
                        <?php } ?>
                    </tbody>
                    
                </table>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="block">
            <div class="block-title">
                <h2>Docencia</h2>
            </div>
            <div class="table-responsive">
                <table id="general-table" class="table table-striped table-vcenter">
                    <thead>
                        <tr>
                            <th class="text-center">#</th>
                            <th>Gestión</th>
                            <th>Institución</th>
                            <th>Asignatura</th>
                            <th>Carga Horaria</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php $c=1; ?>
                        <?php foreach ($docencia as $v) { ?>
                        <tr>
                            <td class="text-center"><?php echo $c; $c++; ?></td>
                            <td><?php echo $v->gestion ?></td>
                            <td><?php echo $v->institucion ?></td>
                            <td><?php echo $v->materia ?></td>
                            <td><?php echo $v->duracion ?></td>
                        </tr>
                        <?php } ?>
                    </tbody>
                    
                </table>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="block">
            <div class="block-title">
                <h2>Referencias Laborales</h2>
            </div>
            <div class="table-responsive">
                <table id="general-table" class="table table-striped table-vcenter">
                    <thead>
                        <tr>
                            <th class="text-center">#</th>
                            <th>Nombre(s) y Apellido(s)</th>
                            <th>Institución</th>
                            <th>Cargo</th>
                            <th>Teléfono</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php $c=1; ?>
                        <?php foreach ($referencia as $v) { ?>
                        <tr>
                            <td class="text-center"><?php echo $c; $c++; ?></td>
                            <td><?php echo $v->nombres_y_apps ?></td>
                            <td><?php echo $v->institucion ?></td>
                            <td><?php echo $v->cargo ?></td>
                            <td><?php echo $v->telefono ?></td>
                        </tr>
                        <?php } ?>
                    </tbody>
                    
                </table>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="block">
            <div class="block-title">
                <h2>Referencias Personales</h2>
            </div>
            <div class="table-responsive">
                <table id="general-table" class="table table-striped table-vcenter">
                    <thead>
                        <tr>
                            <th class="text-center">#</th>
                            <th>Nombre(s) y Apellido(s)</th>
                            <th>Parentesco</th>
                            <th>Teléfono</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php $c=1; ?>
                        <?php foreach ($referenciapersonal as $v) { ?>
                        <tr>
                            <td class="text-center"><?php echo $c; $c++; ?></td>
                            <td><?php echo $v->nombres_y_apps ?></td>
                            <td><?php echo $v->parentesco ?></td>
                            <td><?php echo $v->telefono ?></td>
                        </tr>
                        <?php } ?>
                    </tbody>
                    
                </table>
            </div>
        </div>
    </div>

</div>

