<script type="text/javascript">
$(document).ready(function () {
   
$(".imprimir").click(function(){
   //alert("hoal");
   //var html="<html>";
   var html= document.getElementById('cargar_pagina').innerHTML;

   //html+="</html>";

    var printWin = window.open('','','left=0,top=0,width=1000,height=900,toolbar=0,scrollbars=0,status=0');

   printWin.document.write(html);
   printWin.document.close();
   printWin.focus();
   printWin.print();
   printWin.close();
});

});



</script>
<?php 
$mes_array =array(
                "1" => "ENERO",
                "2"   => "FEBRERO",
                "3" => "MARZO",
                "4" => "ABRIL",
                "5" => "MAYO",
                "6" => "JUNIO",
                "7" => "JULIO",
                "8" => "AGOSTO",
                "9" => "SEPTIEMBRE",
                "10" => "OCTUBRE",
                "11" => "NOVIEMBRE",
                "12" => "DICIEMBRE"
                );

 ?>
<div class="row">
    <div class="col-md-12">
        <div class="block-title">
            <h3 style="color:#2D78D5">
                <i class="gi gi-dashboard"></i>Bienvenido: <?php echo $usuario->nombre.' '.$usuario->app.' '.$usuario->apm; ?>
            </h3>
        </div>
    </div>
</div>

<div class="row">
            <div class="col-md-12"><?php  echo $this->flashSession->output(); ?> </div>
</div>
<input type="button" value="Imprimir Formulario" class="imprimir btn btn-sm btn-primary pull-right"></input>

    <div class="row">
        <div class="col-lg-12">
            <div id="cargar_pagina">
                <?php echo $contenido_html ?>                
            </div>
        </div>
    </div>