<?php
use Phalcon\Tag; ?>
<div class="row">
	<div class="col-md-12">
	<?php if(count($convocatoria)>0){ ?>
		<?php foreach ($convocatoria as $v) { ?>
		<div class="block full">
			<div class="block-title">
				<h2>
					<strong><?php echo $v->codigo_proceso ?></strong>

				</h2>
				<h5>
				Fecha Publicación: <?php echo date("d-m-Y",strtotime($v->fecha_publ)) ?> <br>
				Fecha Conclusión: <?php echo date("d-m-Y", strtotime($v->fecha_concl))  ?>	
				</h5>
				<?php 
				/*$archivo= Archivos::find(array('baja_logica=1 and persona_id='.$v->id,'order'=>'id ASC'));
				foreach ($archivo as $v) { ?>
												
												<a href="/login/descargar/<?php echo $v->id ?>"><?php echo substr($v->nombre_archivo, 15) ?></a>
												<!--  -->
											<?php } */?>
			</div>
			<ol>
				
			
			<?php 
			
			$model = new Ppostulantes();
        	$resul= $model->listacargos($v->id);
        	foreach ($resul as $val) {
        		echo '<li>'.$val->cargo.'</li>';
        	}
			 ?>
			 </ol>
		</div>	
	<?php } ?>
	<?php }	else { ?>
			<div class="alert alert-warning alert-dismissable">
                    <button class="close" aria-hidden="true" data-dismiss="alert" type="button">×</button>
                    <h4>
                        <i class="fa fa-info-circle"></i>
                        Información
                    </h4>
                    Estimado Postulante. Actualmente no hay ningun cargo dentro la convocatoria. Pero usted puede realizar el registro y llenado de su postulación para pasas por el proceso de selección, para futuras convocatorias.
                    <!-- <a class="alert-link" href="javascript:void(0)">day</a>
                    ! -->
                </div>
	<?php	}?>
	
	</div>
</div>