<?php
use Phalcon\Tag; ?>
<div class="row">
	<div class="col-md-12">
	<?php foreach ($convocatoria as $v) { ?>
		<div class="block full">
			<div class="block-title">
				<h2>
					<strong><?php echo $v->codigo_proceso ?></strong>

				</h2>
				<h5>
				Fecha Publicación: <?php echo date("d-m-Y",strtotime($v->fecha_publ)) ?> <br>
				Fecha Conclusión: <?php echo date("d-m-Y", strtotime($v->fecha_concl))  ?>	
				</h5>
				<?php 
				/*$archivo= Archivos::find(array('baja_logica=1 and persona_id='.$v->id,'order'=>'id ASC'));
				foreach ($archivo as $v) { ?>
												
												<a href="/login/descargar/<?php echo $v->id ?>"><?php echo substr($v->nombre_archivo, 15) ?></a>
												<!--  -->
											<?php } */?>
			</div>
			<ol>
				
			
			<?php 
			$model = new Ppostulantes();
        	$resul= $model->listacargos(8);
        	foreach ($resul as $v) {
        		echo '<li>'.$v->cargo.'</li>';
        	}
			 ?>
			 </ol>
		</div>	
	<?php } ?>
	</div>
</div>