<?php
if (isset($_POST['username'])) {
    $user = $_POST['username'];
} else {
    $user = '';
}
?>
<!-- BEGIN ERROR BOX -->
<?php  echo $this->flashSession->output(); ?> 
<div class="alert alert-danger hide">
    <button type="button" class="close" data-dismiss="alert">×</button>
    <h4>Error!</h4>

</div>
<!-- END ERROR BOX -->

<div class="container-page">
    <div class="col-md-6">
        <form action="" method="post">
            <p>Si ya te registrarte ingresa aquí para llenar tu formulario de postulación</p>
            <input type="text" name="username" placeholder="Correo Electronico" value="<?php  echo $user; ?>" class="input-field form-control user" />
            <input type="password" name="password" placeholder="Contraseña" class="input-field form-control password" />
            <button type="submit" class="btn btn-login">Ingresar</button>
            <div class="login-links">
                <a href="/login/password">Olvido su contraseña?</a>
<!--     <br>
    <a href="/login/password">No tengo cuenta? <strong>Registrarme</strong></a> -->
            </div>
        </form>
    </div>
    <div class="col-md-6">
        <h3 class="dark-grey">Terminos y Condiciones</h3>
        <p> Para ser parte del Sistema de Transporte Urbano mas importante del país</p>
        <p> Para ver los puestos disponibles, requisitos y la escala salarial haga click en el link para descargar el archivo. <a href="/login/descargar">descargar aquí</a>  </p>

        <a href="/login/registrar" class="btn btn-login">Registrarme</a>
    </div>
</div>






