<div class="row">
	<div class="col-md-12">
		<div class="widget">
			<div class="widget-advanced widget-advanced-alt">
					<!-- <div class="widget-header text-left">
						<img src="/images/0zmr.jpg" alt="background" class="widget-background animation-pulseSlow" />
					</div> -->
					<div class="widget-main">
						<h4>OBJETIVOS ESTRATÉGICOS</h4>
						<p>“Mi Teleférico” tiene como objetivos estratégicos los siguientes:</p>
						<ol>
							<li>Prestar un servicio de transporte de excelencia.</li>
							<li>Promover la cultura teleférico.</li>
							<li>Consolidar la Empresa Estatal de Transporte por Cable “Mi Teleférico”.</li>
						</ol>
					</div>
				</div>
			</div>
		</div>
	</div>