
<?php
if (isset($_POST['username'])) {
    $user = $_POST['username'];
} else {
    $user = '';
}
?>
<!-- BEGIN ERROR BOX -->
<?php echo $this->flashSession->output(); ?> 
<div class="alert alert-danger hide">
    <button type="button" class="close" data-dismiss="alert">×</button>
    <h4>Error!</h4>

</div>
<!-- END ERROR BOX -->
<form action="" method="POST">
    <p>Ingrese su dirección de correo electrónico debajo y le enviaremos un enlace para restablecer la contraseña a su bandeja de entrada.</p>
    <input type="email" placeholder="Email" name="email" class="input-field" required/>

    <p>
        <img src="/images/cool-php-captcha/captcha.php" id="captcha" />
    </p>
    
    <p>
        <a href="#" onclick="
        document.getElementById('captcha').src='/images/cool-php-captcha/captcha.php?'+Math.random();
        document.getElementById('captcha-form').focus();"
        id="change-image">No puedo leer. Cambiar de texto.</a>
        <input type="text" name="captcha" id="captcha-form" autocomplete="off" placeholder="Ingrese las letras" required />
        <button type="submit" class="btn btn-login btn-reset">Enviar</button>    
    </p>
    <!-- CHANGE TEXT LINK -->

</form>
<div class="login-links">
    <a href="/login">Ya tienes cuenta  <strong>Ingresar</strong></a>
    <br>
    <a href="/login/registrar"> No tienes cuenta <strong> Registrarse</strong></a>
</div>

<?php unset($_SESSION['captcha']); ?>