<div class="row">
    <div class="col-md-12" style="margin-top:2px;">
        <div class="content-header">
            <div class="header-section">
                <h1>
                    <i class="gi gi-notes_2"></i>Registro Unico de Postulantes
                </h1>
            </div>
        </div>
        <div class="panel panel-primary">
            <div class="panel-body" style="padding-top:2px">
            <form action="" method="post">
                <div class="row">
                    <div class="col-md-7">
                        <div class="panel panel-primary">
                            <div class="panel-heading">
                                <div class="panel-title">Datos Personales</div>
                            </div>
                            <div class="panel-body form-horizontal" >
                                <!-- <div class="form-group">
                                    <label class="col-md-4 control-label">Puesto al que Postula <span class="text-danger">*</span></label>
                                    <div class="col-md-8">
                                        <?php // foreach ($cargos as $v) { ?>
                                            <dd><?php // echo $v->cargo ?></dd>

                                        <?php // } ?>
                                    </div>
                                </div> -->
                                <div class="form-group">
                                    <label class="col-md-4 control-label">Lugar de Postulación <span class="text-danger">*</span></label>
                                    <div class="col-md-8">
                                        <select name="lugar_postulacion" id="lugar_postulacion" class="form-control">
                                            <option value="LA PAZ">LA PAZ</option>
                                            <option value="EL ALTO">EL ALTO</option>
                                            <option value="ORURO">ORURO</option>
                                            <option value="POTOSI">POTOSI</option>
                                            <option value="COCHABAMBA">COCHABAMBA</option>
                                            <option value="CHUQUISACA">CHUQUISACA</option>
                                            <option value="TARIJA">TARIJA</option>
                                            <option value="SANTA CRUZ">SANTA CRUZ</option>
                                            <option value="BENI">BENI</option>
                                            <option value="PANDO">PANDO</option>
                                        </select>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="col-md-4 control-label">Nombre(s) <span class="text-danger">*</span></label>
                                    <div class="col-md-8">
                                        <input type="text" id="nombre" name="nombre" class="form-control" placeholder="Nombre(s) completo" required/>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="col-md-4 control-label">Apellido Paterno <span class="text-danger">*</span></label>
                                    <div class="col-md-8">
                                        <input type="text" id="app" name="app" class="form-control" placeholder="Apellido Paterno" required/>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="col-md-4 control-label">Apellido Materno</label>
                                    <div class="col-md-8">
                                        <input type="text" id="apm" name="apm" class="form-control" placeholder="Apellido Materno" />
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="col-md-4 control-label">Sexo <span class="text-danger">*</span></label>
                                    <div class="col-md-8">
                                    <select name="sexo" id="sexo" class="form-control">
                                        <option value="MASCULINO">MASCULINO</option>
                                        <option value="FEMENINO">FEMENINO</option>
                                    </select>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="col-md-4 control-label">Cedula de Identidad <span class="text-danger">*</span></label>
                                    <div class="col-md-4">
                                        <input type="number" id="ci" name="ci" class="form-control" placeholder="Cedula de identidad" required/>
                                    </div>
                                    <div class="col-md-4">
                                        <select name="expedido" id="expedido" class="form-control">
                                            <option value="LA PAZ">LA PAZ</option>
                                            <option value="ORURO">ORURO</option>
                                            <option value="POTOSI">POTOSI</option>
                                            <option value="COCHABAMBA">COCHABAMBA</option>
                                            <option value="CHUQUISACA">CHUQUISACA</option>
                                            <option value="TARIJA">TARIJA</option>
                                            <option value="SANTA CRUZ">SANTA CRUZ</option>
                                            <option value="BENI">BENI</option>
                                            <option value="PANDO">PANDO</option>
                                        </select>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="col-md-4 control-label">Fecha Nacimiento <span class="text-danger">*</span></label>
                                    <div class="col-md-8">
                                        <input type="text" id="fecha_nac" name="fecha_nac" value="01-01-1980" class="form-control input-datepicker-close" data-date-format="dd-mm-yyyy" required/>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="col-md-4 control-label">Nacionalidad</label>
                                    <div class="col-md-8">
                                        <input type="text" id="nacionalidad" name="nacionalidad" class="form-control" placeholder="Nacionalidad" readonly="readonly" value="Boliviano" />
                                    </div>
                                </div>
                                 <div class="form-group">
                                    <label class="col-md-4 control-label">Estado Civil <span class="text-danger">*</span></label>
                                    <div class="col-md-8">
                                    <select name="estado_civil" id="estado_civil" class="form-control">
                                        <option value="SOLTERO">SOLTERO</option>
                                        <option value="CASADO">CASADO</option>
                                        <option value="DIVORCIADO">DIVORCIADO</option>
                                        <option value="VIUDO">VIUDO</option>
                                        <option value="UNION LIBRE">UNION LIBRE</option>
                                    </select>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="col-md-4 control-label">Nro. de Serie de Libreta Militar</label>
                                    <div class="col-md-8">
                                        <input type="text" id="libreta_militar" name="libreta_militar" class="form-control" placeholder="Numero de serie de libreta militar" required/>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="col-md-4 control-label">Certificado de Empadronamiento</label>
                                    <div class="col-md-8">
                                    <select name="empadronamiento" id="empadronamiento" class="form-control">
                                        <option value="NO">NO</option>
                                        <option value="SI">SI</option>
                                    </select>
                                    <span class="help-block">El certificado de empadronamiento debera ser presentado en caso de que sea seleccionado en la postulación.</span>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="col-md-4 control-label">Parentesco <span class="text-danger">*</span></label>
                                    <div class="col-md-8">
                                    <select name="parentesco" id="parentesco" class="form-control">
                                        <option value="NO TIENE PARENTESCO EN LA EMPRESA">NO TIENE PARENTESCO EN LA EMPRESA</option>
                                        <option value="TIENE PARENTESCO EN LA EMPRESA">TIENE PARENTESCO EN LA EMPRESA</option>
                                    </select>
                                    </div>
                                </div>
                                <!-- <div class="form-group">
                                    <div class="col-md-8 col-md-offset-3">
                                        <button type="submit" class="btn btn-sm btn-primary"><i class="fa fa-user"></i> Login</button>
                                        <button type="reset" class="btn btn-sm btn-warning"><i class="fa fa-repeat"></i> Reset</button>
                                    </div>
                                </div> -->
                            

                            </div>
                        </div>  
                    </div>
                    <div class="col-md-5">
                        <div class="panel panel-primary">
                            <div class="panel-heading">
                                <div class="panel-title">Datos Referenciales</div>
                            </div>
                            <div class="panel-body form-horizontal" >
                                <div class="form-group">
                                    <label class="col-md-4 control-label">Dirección Domicilio <span class="text-danger">*</span></label>
                                    <div class="col-md-8">
                                        <input type="text" id="direccion" name="direccion" class="form-control" placeholder="Zona,calle o avenida,nro" required/>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="col-md-4 control-label">Teléfono o Número Referencia <span class="text-danger">*</span></label>
                                    <div class="col-md-8">
                                        <input type="number" id="telefono" name="telefono" class="form-control" placeholder="Numero de telefono" required/>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="col-md-4 control-label">Celular <span class="text-danger">*</span></label>
                                    <div class="col-md-8">
                                        <input type="number" id="celular" name="celular" class="form-control" placeholder="Numero de celular" required/>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="col-md-4 control-label">Correo Electronico <span class="text-danger">*</span></label>
                                    <div class="col-md-8">
                                        <input type="email" id="correo" name="correo" class="form-control" placeholder="correo electronico" required/>
                                    </div>
                                </div>
                                <!-- <div class="form-group">
                                    <label class="col-md-4 control-label">Fax</label>
                                    <div class="col-md-8">
                                        <input type="text" id="fax" name="fax" class="form-control" placeholder=" Numero de fax" />
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="col-md-4 control-label">Casilla de Correo</label>
                                    <div class="col-md-8">
                                        <input type="text" id="casilla" name="casilla" class="form-control" placeholder="Numero de Casilla de correo" />
                                    </div>
                                </div> -->
                                
                                <div class="form-group">
                                    <div class="col-md-8 col-md-offset-3">
                                        <button type="submit" class="btn btn-sm btn-primary"><i class="fa fa-user"></i> Guardar</button>
                                        <a href="/" class="btn btn-sm btn-warning"><i class="fa fa-repeat"></i> Cancelar</a>
                                        <!-- <button type="reset" class="btn btn-sm btn-warning"></button> -->
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                </form>
            </div>
        </div>        
    </div>
</div>

<!-- Modal Reporte-->
<div class="modal fade" id="myModal_rep" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <form class="form-horizontal" id="testForm_rep" data-toggle="validator" action="/login" method="POST" target="_blank" />
            <!-- <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                <h4 class="modal-title" id="titulo">FORMULARIO DE POSTULACIÓN</h4>
            </div> -->
            <div class="modal-body">
                <div class="form-group">
                    <label class="col-md-12" >
                    <p>Este Formulario representa o tiene carácter de Declaración Jurada para los fines legales correspondientes.</p>
                    <p>En caso de que mi postulación sea adjudicada, me comprometo a presentar toda la documentación en original o fotocopia legalizada, aceptando que el incumplimiento es causal de descalificación.</p>
                    </label>
                </div>
                
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Acepto</button>
                <a href="/login" class="btn btn-primary">No Acepto</a>
                <!-- <button type="submit" class="btn btn-primary" id="exportar_pdf">No Acepto</button> -->
            </div>
        </form>
    </div>
</div>
</div>
<!-- end  modal -->
<style type="text/css">
        .datepicker{z-index:1151 !important;}
    </style>