<div class="row">
		<div class="col-md-12">
			<div class="widget">
				<div class="widget-advanced widget-advanced-alt">
					<!-- <div class="widget-header text-left">
						<img src="/images/0zmr.jpg" alt="background" class="widget-background animation-pulseSlow" />
					</div> -->
					<div class="widget-main">
						<h4>VISIÓN</h4>
						<p>"Transportamos Vidas con seguridad, eficiencia, sostenibilidad, calidez e inclusión social para Vivir Bien".</p>
						<h4>MISIÓN</h4>
						<p>“Somos el referente nacional e internacional del transporte urbano, que colma expectativas y nos mejora la vida”.</p>
					</div>
				</div>
			</div>
		</div>
</div>