<!DOCTYPE html>
<html lang="es" class="app">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="Ivan MArcelo">
    <meta name="keyword" content="">
    <link rel="shortcut icon" href="img/favicon.png">
    <?php echo $this->tag->getTitle(); ?>
    <style>
        body{font-family:Roboto,Arial,sans-serif;font-size:11px;font-weight:400;text-decoration:none}
    </style>
    <!-- CSS -->
    <!-- <link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'> -->
    <!--[if IE 8]><script src="/assets/js/helpers/excanvas.min.js"></script><![endif]-->
    <script src="/assets/js/vendor/jquery-1.11.0.min.js"></script>
    <?php $this->assets->outputCss(); ?>
    <!--[if lt IE 9]> <script src="/assets/js/ie/html5shiv.js"></script> <script src="/assets/js/ie/respond.min.js"></script> <script src="/assets/js/ie/excanvas.js"></script> <![endif]-->
    <?php echo $this->assets->outputJs() ?>  
</head>
<body id="page-top" class="index">

    <!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top" style="min-height:100px; position:relative">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header page-scroll">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#page-top">MI TELEFERICO - Postulación en Linea</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li class="hidden">
                        <a href="#page-top"></a>
                    </li>
                    <li class="page-scroll">
                        <a href="#portfolio">Postulación</a>
                    </li>
                    <li>
                        <a href="usuario/logout">SALIR</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container-fluid -->
    </nav>


    <!-- Contact Section -->
    <section >
        <div class="container">
            <div class="row">
                <div class="col-lg-10 col-lg-offset-1">
                    <!-- <div class="content-header">
                        <div class="header-section">
                            <h3>
                                <i class="gi gi-dashboard"></i>Pagina de Inicio<br><small>Bienvenido: <?php echo $usuario->nombre; ?></small>
                            </h3>
                        </div>
                    </div> -->
                    <div id="page-content">                
                        <?php echo $this->getContent(); ?>                  
                    </div>  
                </div>
            </div>
        </div>
    </section>

    <!-- Footer -->
    <footer class="text-center">

        <div class="footer-below">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        Copyright &copy; Your Website 2014
                    </div>
                </div>
            </div>
        </div>
    </footer>

</body>
</html>
