<!DOCTYPE html>
<html lang="es">
    <head>
        <meta charset="utf-8">
        <?php echo $this->tag->getTitle(); ?>   
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="">
        <meta name="author" content="">
        <!-- <link href="/media/less/styles.less" rel="stylesheet/less" media="all">  -->
        <link rel='stylesheet' type='text/css' href='/media/plugins/form-markdown/css/bootstrap-markdown.min.css' /> 
        <link rel='stylesheet' type='text/css' href='/media/js/jqueryui.css' />

<!-- <script type="text/javascript" src="/media/js/less.js"></script> -->
        <?php $this->assets->outputCss(); ?>
    </head>
    <body class="">


        <?php echo $this->getContent(); ?>                                                         

    </div> <!-- page-container -->
    <!--
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
    <script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/jquery-ui.min.js"></script>
    
    <script>!window.jQuery && document.write(unescape('%3Cscript src="/media/js/jquery-1.10.2.min.js"%3E%3C/script%3E'))</script>
    <script type="text/javascript">!window.jQuery.ui && document.write(unescape('%3Cscript src="/media/js/jqueryui-1.10.3.min.js'))</script>
    -->

    <script type='text/javascript' src="/media/js/jquery-1.10.2.min.js"></script>
    <script type='text/javascript' src='/media/js/jqueryui-1.10.3.min.js'></script> 
    <script type='text/javascript' src='/media/js/bootstrap.min.js'></script> 

    <?php echo $this->assets->outputJs(); ?> 
</body>
</html>
