<!DOCTYPE html>
<html lang="es" class="app">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="">
        <meta name="author" content="Ivan MArcelo">
        <meta name="keyword" content="">
        <link rel="shortcut icon" href="img/favicon.png">
        <?php echo $this->tag->getTitle(); ?>
        <style>
            body{font-family:Roboto,Arial,sans-serif;font-size:11px;font-weight:400;text-decoration:none}
        </style>
        <!-- CSS -->
       <!-- <link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'> -->
        <!--[if IE 8]><script src="/assets/js/helpers/excanvas.min.js"></script><![endif]-->
        <script src="/assets/js/vendor/jquery-1.11.0.min.js"></script>


        <script src="/assets/js/vendor/modernizr-2.7.1-respond-1.4.2.min.js"></script>
        <script src="/assets/js/vendor/bootstrap.min.js"></script>
        <script src="/assets//js/plugins.js"></script>
        <script src="/assets/js/app.js"></script>
        <script src="/js/bootbox.js"></script>


        <link rel="stylesheet" href="/assets/css/bootstrap.min.css" />
        <link rel="stylesheet" href="/assets/css/plugins.css" />
        <link rel="stylesheet" href="/assets/css/main.css" />
        <link rel="stylesheet" href="/assets/css/themes.css" />

        <?php // $this->assets->outputCss(); ?>
        <!--[if lt IE 9]> <script src="/assets/js/ie/html5shiv.js"></script> <script src="/assets/js/ie/respond.min.js"></script> <script src="/assets/js/ie/excanvas.js"></script> <![endif]-->
        <?php  // echo $this->assets->outputJs() ?>  
    </head>
    <body>

        <div>
            
            
                    <?php echo $this->getContent(); ?>                  
            
            
        </div>
    </body>
</html>
